clone:
  path: github.com/go-openapi/jsonpointer

matrix:
  GO_VERSION:
    - "1.6"

build:
  integration:
    image: golang:$$GO_VERSION
    pull: true
    commands:
      - go get -u github.com/axw/gocov/gocov
      - go get -u gopkg.in/matm/v1/gocov-html
      - go get -u github.com/cee-dub/go-junit-report
      - go get -u github.com/stretchr/testify/assert
      - go test -v -race -coverprofile=profile.cov -covermode=count ./...

notify:
  slack:
    channel: bots
    webhook_url: $$SLACK_URL
    username: drone

publish:
  coverage:
    server: https://coverage.vmware.run
    token: $$GITHUB_TOKEN
    # threshold: 70
    # must_increase: true
    when:
      matrix:
        GO_VERSION: "1.6"
